version: '3.7'

services:
  otaris-b2b-be:
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    volumes:
      - ./src:/home/node/app/src
      - ./nodemon.json:/home/node/app/nodemon.json
    container_name: otaris-b2b-be
    expose:
      - '5050'
    ports:
      - '5050:5050'
    command: npm run dev
    env_file:
      - .env.dev
    depends_on:
      - mongodb

  mongodb:
    image: mongo
    restart: always
    expose:
      - '27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: otaris1234
      MONGO_INITDB_DATABASE: otarisb2b
